name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-Linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install package
      run: sudo apt-get -y install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
    - name: Build
      run: swift build
